site_name: TR-Sunucu-Wiki
repo_url: https://github.com/TheAlan404/tr-sunucu-wiki
repo_name: TheAlan404/tr-sunucu-wiki
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/server
  palette: 
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
